@extends('layouts.platform')
@section('title', 'Administrateurs plateforme')
@section('page-title', 'Administrateurs plateforme')
@section('content')
<div class="row g-4"><div class="col-xl-5"><div class="platform-card p-4"><h2 class="h5 mb-3">Créer un compte</h2><div class="alert alert-info small">Le nouvel administrateur devra remplacer son mot de passe à sa première connexion.</div><form method="POST" action="{{ route('platform.admins.store') }}">@csrf
<div class="mb-3"><label class="form-label" for="name">Nom complet</label><input id="name" name="name" class="form-control" value="{{ old('name') }}" required></div><div class="mb-3"><label class="form-label" for="email">E-mail</label><input id="email" name="email" type="email" class="form-control" value="{{ old('email') }}" required></div><div class="mb-3"><label class="form-label" for="role">Rôle plateforme</label><select id="role" name="role" class="form-select" required>@foreach($roles as $key=>$definition)<option value="{{ $key }}" @selected(old('role')===$key)>{{ $definition['label'] }}</option>@endforeach</select><div id="roleHelp" class="form-text"></div></div>
<div class="mb-3"><label class="form-label" for="password">Mot de passe initial</label><div class="input-group"><input id="password" name="password" type="password" class="form-control" required><button type="button" class="btn btn-outline-secondary password-toggle" data-target="password"><i class="bi bi-eye"></i></button></div></div><div class="mb-3"><label class="form-label" for="password_confirmation">Confirmer</label><div class="input-group"><input id="password_confirmation" name="password_confirmation" type="password" class="form-control" required><button type="button" class="btn btn-outline-secondary password-toggle" data-target="password_confirmation"><i class="bi bi-eye"></i></button></div><div class="form-text">12 caractères, majuscule, minuscule, chiffre et symbole.</div></div>
<div class="mb-3"><label class="form-label" for="reason">Motif</label><textarea id="reason" name="reason" class="form-control" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></div><div class="mb-4"><label class="form-label" for="current_password">Votre mot de passe plateforme</label><div class="input-group"><input id="current_password" name="current_password" type="password" class="form-control" required><button type="button" class="btn btn-outline-secondary password-toggle" data-target="current_password"><i class="bi bi-eye"></i></button></div></div><button class="btn btn-warning w-100" data-loading-text="Création…"><i class="bi bi-person-plus me-2"></i>Créer l’administrateur</button></form></div></div>
<div class="col-xl-7"><div class="platform-card p-3"><h2 class="h5 mb-3">Comptes existants</h2><div class="table-responsive"><table class="table table-dark table-hover align-middle"><thead><tr><th>Administrateur</th><th>Rôle</th><th>Statut</th><th>Dernière connexion</th><th></th></tr></thead><tbody>@foreach($admins as $admin)<tr><td><strong>{{ $admin->name }}</strong><br><small class="text-secondary">{{ $admin->email }}</small></td><td><span class="badge bg-info text-dark">{{ $admin->roleLabel() }}</span></td><td><span class="badge {{ $admin->is_active?'bg-success':'bg-danger' }}">{{ $admin->is_active?'Actif':'Désactivé' }}</span>@if($admin->must_change_password)<br><small class="text-warning">Mot de passe initial</small>@endif</td><td>{{ $admin->last_login_at?->format('d/m/Y H:i') ?? 'Jamais' }}</td><td><div class="d-flex gap-1"><a href="{{ route('platform.admins.edit',$admin) }}" class="btn btn-sm btn-outline-info"><i class="bi bi-pencil"></i></a>@unless(auth('platform')->id()===$admin->id)<button class="btn btn-sm {{ $admin->is_active?'btn-outline-danger':'btn-outline-success' }} admin-status" data-url="{{ route('platform.admins.status',$admin) }}" data-active="{{ $admin->is_active?'0':'1' }}" data-name="{{ $admin->name }}"><i class="bi {{ $admin->is_active?'bi-person-x':'bi-person-check' }}"></i></button>@endunless</div></td></tr>@endforeach</tbody></table></div>{{ $admins->links() }}</div></div></div>
<div class="platform-card p-3 mt-4">
    <h2 class="h5 mb-3"><i class="bi bi-shield-lock me-2"></i>Sécurité des administrateurs</h2>
    <div class="table-responsive"><table class="table table-dark align-middle mb-0"><thead><tr><th>Compte</th><th>Double authentification</th><th>Action</th></tr></thead><tbody>
    @foreach($admins as $securityAdmin)<tr><td>{{ $securityAdmin->name }}<br><small class="text-secondary">{{ $securityAdmin->email }}</small></td><td><span class="badge {{ $securityAdmin->two_factor_enabled ? 'bg-success' : 'bg-warning text-dark' }}">{{ $securityAdmin->two_factor_enabled ? 'Active' : 'Inactive' }}</span></td><td><div class="d-flex flex-wrap gap-2"><button class="btn btn-sm {{ $securityAdmin->two_factor_enabled ? 'btn-outline-danger' : 'btn-outline-success' }} two-factor-toggle" data-url="{{ route('platform.admins.two-factor.update', $securityAdmin) }}" data-name="{{ $securityAdmin->name }}" data-enabled="{{ $securityAdmin->two_factor_enabled ? '0' : '1' }}"><i class="bi {{ $securityAdmin->two_factor_enabled ? 'bi-shield-x' : 'bi-shield-check' }} me-1"></i>{{ $securityAdmin->two_factor_enabled ? 'Désactiver' : 'Activer' }}</button>@if($securityAdmin->two_factor_enabled)<button class="btn btn-sm btn-outline-warning two-factor-reset" data-url="{{ route('platform.admins.two-factor.reset', $securityAdmin) }}" data-name="{{ $securityAdmin->name }}"><i class="bi bi-arrow-clockwise me-1"></i>Réinitialiser</button>@endif</div></td></tr>@endforeach
    </tbody></table></div>
</div>
@endsection
@push('scripts')<script>
const roleDefinitions=@json($roles);const roleSelect=document.getElementById('role'),refreshRole=()=>document.getElementById('roleHelp').textContent=roleDefinitions[roleSelect.value]?.description||'';roleSelect.addEventListener('change',refreshRole);refreshRole();document.querySelectorAll('.password-toggle').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById(b.dataset.target),s=i.type==='password';i.type=s?'text':'password';b.querySelector('i').className=s?'bi bi-eye-slash':'bi bi-eye'}));document.querySelectorAll('.admin-status').forEach(button=>button.addEventListener('click',()=>{const activating=button.dataset.active==='1';Swal.fire({title:(activating?'Réactiver ':'Désactiver ')+button.dataset.name+' ?',icon:'warning',html:'<input id="statusReason" class="swal2-input" placeholder="Motif obligatoire"><input id="statusPassword" type="password" class="swal2-input" placeholder="Votre mot de passe plateforme">',showCancelButton:true,confirmButtonText:activating?'Réactiver':'Désactiver',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),preConfirm:async()=>{const reason=document.getElementById('statusReason').value,password=document.getElementById('statusPassword').value;if(reason.trim().length<5)return Swal.showValidationMessage('Motif de 5 caractères minimum.');if(!password)return Swal.showValidationMessage('Saisissez votre mot de passe.');const r=await fetch(button.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({_method:'PATCH',is_active:activating?1:0,reason:reason.trim(),current_password:password})});const d=await r.json().catch(()=>({}));if(!r.ok)return Swal.showValidationMessage(d.errors?Object.values(d.errors).flat().join(' '):(d.message||'Opération impossible.'));return d}}).then(r=>{if(r.isConfirmed)location.reload()})}));
document.querySelectorAll('.two-factor-reset').forEach(button=>button.addEventListener('click',()=>{Swal.fire({title:'Réinitialiser la sécurité de '+button.dataset.name+' ?',icon:'warning',html:'<input id="resetReason" class="swal2-input" placeholder="Motif obligatoire"><input id="resetPassword" type="password" class="swal2-input" placeholder="Votre mot de passe plateforme">',showCancelButton:true,confirmButtonText:'Oui, réinitialiser',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),preConfirm:async()=>{const reason=document.getElementById('resetReason').value,password=document.getElementById('resetPassword').value;if(reason.trim().length<5)return Swal.showValidationMessage('Motif de 5 caractères minimum.');if(!password)return Swal.showValidationMessage('Saisissez votre mot de passe.');const r=await fetch(button.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({reason:reason.trim(),current_password:password})});const d=await r.json().catch(()=>({}));if(!r.ok)return Swal.showValidationMessage(d.errors?Object.values(d.errors).flat().join(' '):(d.message||'Opération impossible.'));return d}}).then(r=>{if(r.isConfirmed)location.reload()})}));
document.querySelectorAll('.two-factor-toggle').forEach(button=>button.addEventListener('click',()=>{const enabling=button.dataset.enabled==='1',verb=enabling?'Activer':'Désactiver';Swal.fire({title:verb+' la double authentification ?',text:button.dataset.name,icon:enabling?'question':'warning',html:`<p>${button.dataset.name}</p><input id="toggleReason" class="swal2-input" placeholder="Motif obligatoire"><input id="togglePassword" type="password" class="swal2-input" placeholder="Votre mot de passe plateforme">`,showCancelButton:true,confirmButtonText:enabling?'Oui, activer':'Oui, désactiver',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),preConfirm:async()=>{const reason=document.getElementById('toggleReason').value,password=document.getElementById('togglePassword').value;if(reason.trim().length<5)return Swal.showValidationMessage('Motif de 5 caractères minimum.');if(!password)return Swal.showValidationMessage('Saisissez votre mot de passe.');const r=await fetch(button.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({_method:'PATCH',enabled:enabling?1:0,reason:reason.trim(),current_password:password})});const d=await r.json().catch(()=>({}));if(!r.ok)return Swal.showValidationMessage(d.errors?Object.values(d.errors).flat().join(' '):(d.message||'Opération impossible.'));return d}}).then(r=>{if(r.isConfirmed)location.reload()})}));
</script>@endpush
