@extends('layouts.platform')
@section('title', 'Paramètres plateforme')
@section('page-title', 'Paramètres plateforme')
@section('content')
<div class="d-flex gap-2 mb-4"><a class="btn btn-outline-light" href="{{ route('platform.settings.general') }}">Général</a><a class="btn btn-warning" href="{{ route('platform.settings.edit') }}">Tarifs et coûts</a></div>
<div class="row g-4"><div class="col-xl-7"><div class="platform-card p-4">
<h2 class="h5">Tarifs et coûts des communications</h2><p class="text-secondary">Les changements s’appliquent uniquement aux nouveaux checkouts.</p>
<form id="pricingForm" method="POST" action="{{ route('platform.settings.pricing.update') }}">@csrf @method('PUT')
<div class="row g-3">
<div class="col-md-6"><label for="sms_unit_price" class="form-label">Prix de vente SMS</label><div class="input-group"><input id="sms_unit_price" name="sms_unit_price" type="number" min="1" max="10000" class="form-control" value="{{ old('sms_unit_price',$smsUnitPrice) }}" required><span class="input-group-text">XOF</span></div></div>
<div class="col-md-6"><label for="whatsapp_unit_price" class="form-label">Prix de vente WhatsApp</label><div class="input-group"><input id="whatsapp_unit_price" name="whatsapp_unit_price" type="number" min="1" max="10000" class="form-control" value="{{ old('whatsapp_unit_price',$whatsappUnitPrice) }}" required><span class="input-group-text">XOF</span></div></div>
<div class="col-md-6"><label for="sms_unit_cost" class="form-label">Coût fournisseur SMS</label><div class="input-group"><input id="sms_unit_cost" name="sms_unit_cost" type="number" min="0" max="10000" class="form-control" value="{{ old('sms_unit_cost',$smsUnitCost) }}" required><span class="input-group-text">XOF</span></div></div>
<div class="col-md-6"><label for="whatsapp_unit_cost" class="form-label">Coût fournisseur WhatsApp</label><div class="input-group"><input id="whatsapp_unit_cost" name="whatsapp_unit_cost" type="number" min="0" max="10000" class="form-control" value="{{ old('whatsapp_unit_cost',$whatsappUnitCost) }}" required><span class="input-group-text">XOF</span></div></div>
</div>
<div class="mt-3"><label for="reason" class="form-label">Raison</label><textarea id="reason" name="reason" class="form-control" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></div>
<div class="mt-3"><label for="current_password" class="form-label">Mot de passe plateforme</label><div class="input-group"><input id="current_password" name="current_password" type="password" class="form-control" required><button type="button" class="btn btn-outline-secondary password-toggle" data-target="current_password"><i class="bi bi-eye"></i></button></div></div>
<div class="alert alert-info mt-4"><strong>Aperçu pour 100 unités :</strong><br>SMS : CA <span id="smsPreview">{{ number_format($smsUnitPrice*100,0,',',' ') }}</span> XOF, bénéfice <strong id="smsProfitPreview">{{ number_format(($smsUnitPrice-$smsUnitCost)*100,0,',',' ') }}</strong> XOF.<br>WhatsApp : CA <span id="whatsappPreview">{{ number_format($whatsappUnitPrice*100,0,',',' ') }}</span> XOF, bénéfice <strong id="whatsappProfitPreview">{{ number_format(($whatsappUnitPrice-$whatsappUnitCost)*100,0,',',' ') }}</strong> XOF.</div>
<button class="btn btn-warning btn-lg" data-loading-text="Enregistrement…">Enregistrer les tarifs et coûts</button></form></div></div>
<div class="col-xl-5"><div class="platform-card p-3"><h2 class="h5">Historique récent</h2><div class="table-responsive"><table class="table table-dark"><thead><tr><th>Élément</th><th>Changement</th><th>Motif</th></tr></thead><tbody>@php($labels=[\App\Services\PlatformPricingService::SMS_KEY=>'Vente SMS',\App\Services\PlatformPricingService::WHATSAPP_KEY=>'Vente WhatsApp',\App\Services\PlatformPricingService::SMS_COST_KEY=>'Coût SMS',\App\Services\PlatformPricingService::WHATSAPP_COST_KEY=>'Coût WhatsApp']) @forelse($history as $entry)<tr><td>{{ $labels[$entry->key]??$entry->key }}</td><td>{{ $entry->old_value }} → <strong>{{ $entry->new_value }}</strong></td><td><small>{{ $entry->reason }}<br>{{ $entry->admin?->name }}</small></td></tr>@empty<tr><td colspan="3" class="text-center text-secondary">Aucun changement.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
@push('scripts')<script>
const pf=new Intl.NumberFormat('fr-FR'),pv=id=>parseInt(document.getElementById(id).value,10)||0,refresh=()=>{smsPreview.textContent=pf.format(pv('sms_unit_price')*100);whatsappPreview.textContent=pf.format(pv('whatsapp_unit_price')*100);smsProfitPreview.textContent=pf.format((pv('sms_unit_price')-pv('sms_unit_cost'))*100);whatsappProfitPreview.textContent=pf.format((pv('whatsapp_unit_price')-pv('whatsapp_unit_cost'))*100)};['sms_unit_price','whatsapp_unit_price','sms_unit_cost','whatsapp_unit_cost'].forEach(id=>document.getElementById(id).addEventListener('input',refresh));document.querySelector('.password-toggle').addEventListener('click',function(){const input=document.getElementById(this.dataset.target),show=input.type==='password';input.type=show?'text':'password';this.querySelector('i').className=show?'bi bi-eye-slash':'bi bi-eye'});pricingForm.addEventListener('submit',function(e){e.preventDefault();const form=this;if(!form.reportValidity())return;Swal.fire({title:'Confirmer les valeurs ?',html:`SMS : vente <b>${pv('sms_unit_price')}</b>, coût ${pv('sms_unit_cost')} XOF<br>WhatsApp : vente <b>${pv('whatsapp_unit_price')}</b>, coût ${pv('whatsapp_unit_cost')} XOF`,icon:'warning',showCancelButton:true,confirmButtonText:'Oui, enregistrer',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),preConfirm:async()=>{const r=await fetch(form.action,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)});if(!r.ok){const d=await r.json().catch(()=>({}));return Swal.showValidationMessage(d.errors?Object.values(d.errors).flat().join(' '):(d.message||'Erreur'));}return true}}).then(r=>{if(r.isConfirmed)location.reload()})});
</script>@endpush
