@extends('layouts.platform')
@section('title','Paramètres généraux')
@section('page-title','Paramètres généraux')
@section('content')
<div class="d-flex gap-2 mb-4"><a class="btn btn-warning" href="{{ route('platform.settings.general') }}">Général</a><a class="btn btn-outline-light" href="{{ route('platform.settings.edit') }}">Tarifs et coûts</a></div>
<form method="POST" action="{{ route('platform.settings.general.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="row g-4"><div class="col-xl-7">
<div class="platform-card p-4 mb-4"><h2 class="h5">Identité et support</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Nom de l’application</label><input class="form-control" name="app_name" value="{{ old('app_name',$values['identity.app_name']) }}" required></div><div class="col-md-6"><label class="form-label">Logo</label><input class="form-control" type="file" name="logo" accept="image/png,image/jpeg,image/webp"></div><div class="col-md-6"><label class="form-label">E-mail du support</label><input class="form-control" type="email" name="support_email" value="{{ old('support_email',$values['support.email']) }}"></div><div class="col-md-6"><label class="form-label">Téléphone du support</label><input class="form-control" name="support_phone" value="{{ old('support_phone',$values['support.phone']) }}"></div><div class="col-12"><label class="form-label">Horaires du support</label><input class="form-control" name="support_hours" value="{{ old('support_hours',$values['support.hours']) }}"></div><div class="col-md-6"><label class="form-label">Devise par défaut</label><input class="form-control" name="currency" maxlength="3" value="{{ old('currency',$values['defaults.currency']) }}" required></div><div class="col-md-6"><label class="form-label">Pays par défaut</label><input class="form-control" name="country" maxlength="2" value="{{ old('country',$values['defaults.country']) }}" required></div></div></div>
<div class="platform-card p-4 mb-4"><h2 class="h5">Services externes</h2><p class="text-secondary">Les secrets restent dans le fichier .env et ne sont jamais affichés ici.</p>@foreach(['email'=>'E-mail','sms'=>'SMS','whatsapp'=>'WhatsApp','kprimepay'=>'KPrimePay'] as $key=>$label)<div class="d-flex justify-content-between align-items-center border-bottom py-3"><div><strong>{{ $label }}</strong> <span class="badge {{ $serviceStatus[$key]?'bg-success':'bg-danger' }}">{{ $serviceStatus[$key]?'Clé/configuration détectée':'Non configuré' }}</span></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="{{ $key }}_enabled" value="1" @checked(filter_var($values['services.'.$key.'.enabled'],FILTER_VALIDATE_BOOLEAN))></div></div>@endforeach</div>
<div class="platform-card p-4"><h2 class="h5">Délais de sécurité</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Invitation (heures)</label><input class="form-control" type="number" name="invitation_expiry_hours" min="1" max="720" value="{{ $values['security.invitation_expiry_hours'] }}" required></div><div class="col-md-4"><label class="form-label">Code 2FA (minutes)</label><input class="form-control" type="number" name="two_factor_expiry_minutes" min="2" max="60" value="{{ $values['security.two_factor_expiry_minutes'] }}" required></div><div class="col-md-4"><label class="form-label">Paiement (heures)</label><input class="form-control" type="number" name="payment_expiry_hours" min="1" max="720" value="{{ $values['security.payment_expiry_hours'] }}" required></div></div></div>
</div><div class="col-xl-5"><div class="platform-card p-4 mb-4"><h2 class="h5 text-warning">Mode maintenance</h2><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="maintenance_enabled" value="1" @checked(filter_var($values['maintenance.enabled'],FILTER_VALIDATE_BOOLEAN))><label class="form-check-label">Bloquer temporairement l’application POS</label></div><textarea class="form-control" name="maintenance_message" minlength="10" maxlength="500" rows="4" required>{{ old('maintenance_message',$values['maintenance.message']) }}</textarea><div class="form-text">La console SaaS et les webhooks API restent accessibles.</div></div><div class="platform-card p-4 mb-4"><label class="form-label">Motif de la modification</label><textarea class="form-control" name="reason" minlength="5" maxlength="500" required></textarea><label class="form-label mt-3">Votre mot de passe plateforme</label><input class="form-control" type="password" name="current_password" required><button class="btn btn-warning btn-lg w-100 mt-4" data-loading-text="Enregistrement…">Enregistrer les paramètres</button></div><div class="platform-card p-3"><h2 class="h5">Historique récent</h2><div style="max-height:420px;overflow:auto">@forelse($history as $entry)<div class="border-bottom py-2"><small class="text-warning">{{ $entry->key }}</small><br><span>{{ Str::limit($entry->old_value,30) }} → <strong>{{ Str::limit($entry->new_value,30) }}</strong></span><br><small class="text-secondary">{{ $entry->admin?->name }} — {{ $entry->reason }}</small></div>@empty<p class="text-secondary">Aucun changement.</p>@endforelse</div></div></div></div></form>
@endsection
