<?php
namespace Tests\Feature;
use App\Models\{Company,PlatformAdmin,SubscriptionPayment,SubscriptionPlan,User}; use App\Notifications\SubscriptionActivatedNotification; use App\Services\{SubscriptionAccountService,SubscriptionCheckoutService,SubscriptionSettlementService}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Notification; use Tests\TestCase;
class SubscriptionPaymentTest extends TestCase { use RefreshDatabase;
 private function account(): array { $user=User::factory()->create();$company=Company::create(['name'=>'Compte abonnement','email'=>'billing@example.test','number1'=>'90000000','created_by'=>$user->id]);$account=app(SubscriptionAccountService::class)->ensureFor($company,$user->id);return [$user,$company->fresh(),$account]; }
 public function test_downgrade_is_rejected_before_checkout(): void { [$user,$company,$account]=$this->account();$gold=SubscriptionPlan::where('key','gold')->with('features')->firstOrFail();$account->subscriptions()->create(['subscription_plan_id'=>$gold->id,'status'=>'active','billing_period'=>'monthly','starts_at'=>now(),'ends_at'=>now()->addMonth(),'snapshot'=>app(SubscriptionAccountService::class)->snapshot($gold)]);$this->expectException(\RuntimeException::class);app(SubscriptionCheckoutService::class)->create($company->id,$user->id,'basic','monthly'); }
 public function test_verified_payment_is_settled_once_and_credits_annual_quotas_once(): void { [$user,$company,$account]=$this->account();$plan=SubscriptionPlan::where('key','bronze')->with('features')->firstOrFail();$payment=SubscriptionPayment::create(['subscription_account_id'=>$account->id,'subscription_plan_id'=>$plan->id,'user_id'=>$user->id,'transaction_id'=>'SUB-TEST-1','idempotency_key'=>'subscription-test-1','operation'=>'upgrade','billing_period'=>'annual','amount_ht'=>55000,'tax_amount'=>0,'amount'=>55000,'currency'=>'XOF','snapshot'=>app(SubscriptionAccountService::class)->snapshot($plan),'status'=>'pending']);$service=app(SubscriptionSettlementService::class);$verified=['status'=>'success','transaction_currency'=>'XOF','transaction_amount'=>55000];$this->assertTrue($service->creditVerified($payment,$verified,'event-test-1','kpp-test-1'));$this->assertFalse($service->creditVerified($payment->fresh(),$verified,'event-test-1','kpp-test-1'));$company=$company->fresh();$this->assertSame(243,(int)$company->sms_count);$this->assertSame(243,(int)$company->whatsapp_count);$this->assertDatabaseHas('subscription_payments',['transaction_id'=>'SUB-TEST-1','status'=>'paid']); }
 public function test_verified_payment_notifies_each_active_platform_admin_once_with_subscription_details(): void { Notification::fake(); [$user,$company,$account]=$this->account();$admin=PlatformAdmin::create(['name'=>'Finance SaaS','email'=>'finance@example.test','password'=>'secret','role'=>'finance','is_active'=>true,'must_change_password'=>false]);$plan=SubscriptionPlan::where('key','bronze')->with('features')->firstOrFail();$payment=SubscriptionPayment::create(['subscription_account_id'=>$account->id,'subscription_plan_id'=>$plan->id,'user_id'=>$user->id,'transaction_id'=>'SUB-ADMIN-NOTIFY','idempotency_key'=>'subscription-admin-notify','operation'=>'renewal','billing_period'=>'monthly','duration_months'=>3,'amount_ht'=>15000,'tax_amount'=>0,'amount'=>15000,'currency'=>'XOF','snapshot'=>array_merge(app(SubscriptionAccountService::class)->snapshot($plan),['duration_months'=>3]),'status'=>'pending']);$verified=['status'=>'success','transaction_currency'=>'XOF','transaction_amount'=>15000];$service=app(SubscriptionSettlementService::class);$this->assertTrue($service->creditVerified($payment,$verified,'event-admin-notify','kpp-admin-notify'));$this->assertFalse($service->creditVerified($payment->fresh(),$verified,'event-admin-notify','kpp-admin-notify'));Notification::assertSentTo($admin,SubscriptionActivatedNotification::class,function($notification)use($admin,$company,$payment){$rendered=$notification->toMail($admin)->render();return str_contains($rendered,$company->name)&&str_contains($rendered,'3 mois')&&str_contains($rendered,'15 000 XOF')&&str_contains($rendered,$payment->transaction_id);});Notification::assertCount(1);$this->assertDatabaseCount('subscription_events',1); }
}
