@extends('layouts.marketing')
@section('title', 'Encaissez ici. Votre client reçoit sa facture sur son téléphone.')
@section('meta-description', 'Maxanou vous aide à encaisser rapidement, suivre le stock, piloter la caisse et envoyer les reçus par SMS ou WhatsApp.')
@section('content')
<section class="marketing-hero">
    <div class="marketing-container marketing-hero-grid">
        <div class="marketing-hero-copy">
            <span class="marketing-eyebrow">Le commerce, avec plus de contrôle</span>
            <h1>Encaissez ici. Votre client reçoit sa facture sur son téléphone.</h1>
            <p class="marketing-lead">Un POS complet pour vendre, suivre le stock, piloter la caisse et envoyer les reçus par SMS ou WhatsApp.</p>
            <div class="marketing-hero-actions"><a class="marketing-button marketing-button-primary marketing-button-large" data-event="hero_try" href="{{ route('marketing.register') }}">Essayer gratuitement · 14 jours @include('marketing.components.icon', ['name' => 'arrow'])</a><a class="marketing-button marketing-button-secondary marketing-button-large" data-scroll-to="signature-demo" data-event="demo_play" href="#signature-demo">Voir la démonstration</a></div>
            <p class="marketing-login-note">Déjà client ? <a href="{{ route('marketing.login') }}">Se connecter</a></p>
            <div class="marketing-proof-row"><span>@include('marketing.components.icon', ['name' => 'check']) PWA mobile</span><span>@include('marketing.components.icon', ['name' => 'layers']) Plusieurs entreprises</span><span>@include('marketing.components.icon', ['name' => 'shield']) Données séparées</span><span>@include('marketing.components.icon', ['name' => 'file']) Exports</span></div>
        </div>
        <div class="product-window product-window-hero" aria-label="Aperçu fictif du point de vente">
            <div class="product-window-bar"><span class="window-dots"><i></i><i></i><i></i></span><span>Vente rapide</span><span class="product-live"><i></i> Connecté</span></div>
            <div class="product-window-body"><div class="product-sidebar-mini"><b>P</b><span></span><span></span><span></span><span></span></div><div class="product-catalog"><div class="product-window-heading"><div><small>Compagnie active</small><strong>Boutique Démo</strong></div><span class="product-date">Aujourd’hui</span></div><div class="product-search">Rechercher un produit <span>⌕</span></div><div class="product-cards"><div class="product-card"><span class="product-thumb product-thumb-orange">CA</span><strong>Café arabica</strong><small>2 500 FCFA</small></div><div class="product-card"><span class="product-thumb product-thumb-green">MI</span><strong>Miel local</strong><small>4 000 FCFA</small></div><div class="product-card"><span class="product-thumb product-thumb-blue">SA</span><strong>Sac en toile</strong><small>8 500 FCFA</small></div><div class="product-card"><span class="product-thumb product-thumb-pink">BO</span><strong>Bol tressé</strong><small>6 000 FCFA</small></div></div></div><div class="product-cart"><div class="cart-heading"><strong>Panier actuel</strong><span>2 articles</span></div><div class="cart-line"><span>Café arabica × 2</span><b>5 000</b></div><div class="cart-line"><span>Miel local × 1</span><b>4 000</b></div><div class="cart-total"><span>Total</span><strong>9 000 FCFA</strong></div><div class="cart-receipt"><i>@include('marketing.components.icon', ['name' => 'message'])</i><span>Reçu prêt à envoyer<br><small>SMS · WhatsApp selon configuration</small></span></div><button type="button" class="product-pay-button">Encaisser @include('marketing.components.icon', ['name' => 'arrow'])</button></div></div>
        </div>
    </div>
</section>

<section class="marketing-trust-strip"><div class="marketing-container"><span class="marketing-trust-label">Pensé pour les équipes qui veulent</span><span>vendre plus vite</span><span>réduire les erreurs</span><span>servir mieux</span><span>voir juste</span></div></section>

<section class="marketing-section marketing-demo-section" id="signature-demo">
    <div class="marketing-container"><div class="marketing-section-heading marketing-section-heading-split"><div><span class="marketing-eyebrow">La démonstration signature</span><h2>De l’article au téléphone, en quelques secondes.</h2></div><div class="marketing-demo-controls"><span class="marketing-demo-status" data-demo-status>Lecture automatique · 5 secondes</span><button class="marketing-icon-button" type="button" data-demo-toggle aria-label="Mettre la démonstration en pause">@include('marketing.components.icon', ['name' => 'pause'])</button></div></div><div class="signature-demo" data-demo><div class="demo-step is-active" data-demo-step="1"><span class="demo-step-number">01</span><div class="demo-screen"><div class="demo-screen-top">Point de vente <span>+</span></div><div class="demo-demo-product"><span class="product-thumb product-thumb-orange">CA</span><div><strong>Café arabica</strong><small>2 500 FCFA · Disponible</small></div><b>+1</b></div><div class="demo-screen-total">Panier <strong>2 500 FCFA</strong></div></div><strong>Ajoutez un produit</strong><p>Le catalogue reste lisible et rapide.</p></div><div class="demo-step" data-demo-step="2"><span class="demo-step-number">02</span><div class="demo-screen"><div class="demo-screen-top">Paiement confirmé <span class="demo-check">✓</span></div><div class="demo-amount">2 500 <small>FCFA</small></div><div class="demo-change"><span>Reçu</span><b>3 000 FCFA</b><span>Monnaie</span><b>500 FCFA</b></div></div><strong>Confirmez le paiement</strong><p>Total, montant reçu et monnaie visibles.</p></div><div class="demo-step" data-demo-step="3"><span class="demo-step-number">03</span><div class="demo-screen"><div class="demo-screen-top">Reçu généré <span class="demo-check">✓</span></div><div class="demo-receipt"><b>Boutique Démo</b><span>Vente #DÉMO-001</span><span>Café arabica × 1 <i>2 500 FCFA</i></span><hr><strong>Total <i>2 500 FCFA</i></strong></div></div><strong>Le reçu est prêt</strong><p>Un document clair, consultable et exportable.</p></div><div class="demo-step" data-demo-step="4"><span class="demo-step-number">04</span><div class="demo-screen demo-phone-screen"><div class="phone-notch"></div><div class="phone-message"><span>Reçu de Boutique Démo</span><strong>Merci pour votre achat.</strong><small>Votre facture est disponible.</small><b>Voir le reçu</b></div></div><strong>Votre client est informé</strong><p>Par SMS ou WhatsApp, selon le canal configuré et le quota disponible.</p></div></div></div>
</section>

<section class="marketing-section marketing-results-section"><div class="marketing-container"><div class="marketing-section-heading"><span class="marketing-eyebrow">Ce que cela change au quotidien</span><h2>Moins de dispersion. Plus de décisions utiles.</h2><p>Chaque écran vous ramène à ce qui fait avancer le commerce : une vente, un stock, une caisse, un client.</p></div><div class="marketing-metric-grid"><div class="marketing-metric-card"><span class="metric-icon">@include('marketing.components.icon', ['name' => 'cart'])</span><strong>Vendre plus vite</strong><p>Un panier simple, des produits faciles à retrouver, un total toujours sous les yeux.</p></div><div class="marketing-metric-card"><span class="metric-icon metric-icon-green">@include('marketing.components.icon', ['name' => 'check'])</span><strong>Réduire les erreurs</strong><p>Les montants, remises et mouvements de caisse suivent le même flux.</p></div><div class="marketing-metric-card"><span class="metric-icon metric-icon-blue">@include('marketing.components.icon', ['name' => 'people'])</span><strong>Fidéliser naturellement</strong><p>Un reçu clair et un historique client rendent le service plus professionnel.</p></div><div class="marketing-metric-card"><span class="metric-icon metric-icon-purple">@include('marketing.components.icon', ['name' => 'boxes'])</span><strong>Garder le contrôle</strong><p>Catalogue, inventaire et caisse donnent une même lecture de l’activité.</p></div></div></div></section>

<section class="marketing-section marketing-modules-section"><div class="marketing-container"><div class="marketing-section-heading marketing-section-heading-split"><div><span class="marketing-eyebrow">Un produit qui grandit avec vous</span><h2>Les bons outils, au moment où vous en avez besoin.</h2></div><a class="marketing-text-link" href="{{ route('marketing.features') }}">Voir toutes les fonctionnalités @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="marketing-feature-grid">@foreach([['cart','Vente','Encaissez, appliquez une remise, rendez la monnaie.'],['boxes','Catalogue & inventaire','Produits, catégories, entrées, sorties et seuils.'],['wallet','Caisse','Suivez les opérations et les soldes avec une vue claire.'],['people','Clients','Retrouvez les clients et leur historique de ventes.'],['team','Équipe','Invitez, attribuez des rôles et limitez les accès.'],['message','Communication','Consultez les envois et configurez les canaux autorisés.'],['store','E-commerce','Recevez une commande et contrôlez son passage en vente.'],['file','Rapports & exports','Tableaux de bord, historiques, CSV, Excel et PDF.']] as $module)<a class="marketing-feature-card" href="{{ route('marketing.features') }}"><span class="feature-card-icon">@include('marketing.components.icon', ['name' => $module[0]])</span><span><strong>{{ $module[1] }}</strong><small>{{ $module[2] }}</small></span>@include('marketing.components.icon', ['name' => 'arrow'])</a>@endforeach</div></div></section>

<section class="marketing-section marketing-split-section"><div class="marketing-container marketing-split-grid"><div class="marketing-copy-block"><span class="marketing-eyebrow">Du comptoir au téléphone</span><h2>Votre équipe garde le même fil, où qu’elle travaille.</h2><p>Sur ordinateur, tablette, mobile ou PWA, l’interface reste centrée sur les gestes qui comptent. Le panier persistant vous évite de recommencer après une coupure ou une pause.</p><ul class="marketing-check-list"><li>@include('marketing.components.icon', ['name' => 'check']) Interface adaptée aux écrans modestes</li><li>@include('marketing.components.icon', ['name' => 'check']) Panier persistant sur le même contexte</li><li>@include('marketing.components.icon', ['name' => 'check']) Navigation pensée pour le tactile</li></ul></div><div class="device-stack"><div class="device-desktop"><div class="device-bar"><i></i><i></i><i></i></div><div class="device-content"><span></span><span></span><span></span><b>9 000 FCFA</b></div></div><div class="device-phone"><div class="phone-speaker"></div><div class="device-phone-header">Mon activité</div><div class="device-phone-card"><small>Ventes du jour</small><b>48 500</b><span>+12,4 %</span></div><div class="device-phone-lines"><i></i><i></i><i></i></div></div></div></div></section>

<section class="marketing-section marketing-ecommerce-section"><div class="marketing-container marketing-ecommerce-panel"><div><span class="marketing-eyebrow">E-commerce relié</span><h2>Une commande en ligne, puis une décision de vente.</h2><p>Votre boutique publique s’appuie sur le catalogue. La commande est ensuite confirmée et convertie en vente depuis l’espace autorisé, sans fausse promesse de réservation de stock.</p><a class="marketing-button marketing-button-secondary" href="{{ route('marketing.features') }}">Comprendre le parcours @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="ecommerce-flow"><div><span>01</span><strong>Boutique</strong><small>Le client commande</small></div><i>@include('marketing.components.icon', ['name' => 'arrow'])</i><div><span>02</span><strong>Contrôle</strong><small>Vous vérifiez la commande</small></div><i>@include('marketing.components.icon', ['name' => 'arrow'])</i><div><span>03</span><strong>Vente</strong><small>Le stock est traité</small></div></div></div></section>

<section class="marketing-section marketing-security-section"><div class="marketing-container marketing-security-grid"><div><span class="marketing-eyebrow">Confiance intégrée</span><h2>Le contrôle n’est pas une option cachée.</h2><p>Isolation par entreprise, permissions, historique et vérifications côté serveur : les fondations protègent les opérations sans compliquer le quotidien.</p><a class="marketing-text-link" href="{{ route('marketing.security') }}">Voir notre approche sécurité @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="security-proof-list"><div><span>@include('marketing.components.icon', ['name' => 'shield'])</span><strong>Données séparées</strong><small>Chaque entreprise garde son contexte.</small></div><div><span>@include('marketing.components.icon', ['name' => 'lock'])</span><strong>Accès maîtrisés</strong><small>Les rôles limitent les fonctions visibles.</small></div><div><span>@include('marketing.components.icon', ['name' => 'check'])</span><strong>Paiements vérifiés</strong><small>Les confirmations se font côté serveur.</small></div></div></div></section>

<section class="marketing-section marketing-sectors-section"><div class="marketing-container"><div class="marketing-section-heading marketing-section-heading-split"><div><span class="marketing-eyebrow">Des métiers, une même exigence</span><h2>Commencez avec votre réalité.</h2></div><a class="marketing-text-link" href="{{ route('marketing.sectors') }}">Découvrir les secteurs @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="marketing-sector-row">@foreach([['store','Boutique'],['basket','Alimentation'],['tag','Mode'],['scissors','Salon'],['truck','Grossiste'],['buildings','Réseau']] as $sector)<a class="marketing-sector-card" href="{{ route('marketing.sectors') }}">@include('marketing.components.icon', ['name' => $sector[0]])<strong>{{ $sector[1] }}</strong></a>@endforeach</div></div></section>

<section class="marketing-section marketing-pricing-section" id="tarifs"><div class="marketing-container"><div class="marketing-section-heading marketing-section-heading-split"><div><span class="marketing-eyebrow">Des prix lisibles en FCFA</span><h2>Essayez d’abord. Choisissez ensuite.</h2><p>{{ $pricingNote }}</p></div><a class="marketing-text-link" href="{{ route('marketing.pricing') }}">Voir les détails des offres @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="pricing-preview-grid">@foreach($pricing as $plan)<article class="pricing-card @if($plan['featured']) is-featured @endif"><div class="pricing-card-top"><span>{{ $plan['name'] }}</span>@if($plan['featured'])<em>Recommandé</em>@endif</div><div class="pricing-price"><strong>{{ number_format($plan['price'], 0, ',', ' ') }}</strong><small>FCFA HT / {{ $plan['period'] }}</small></div><p>{{ $plan['description'] }}</p><span class="pricing-limits">{{ $plan['limits'] }}</span><span class="pricing-limits">{{ $plan['quota'] }}</span></article>@endforeach</div><p class="pricing-disclaimer">Les offres payantes seront activées après validation du moteur d’abonnement. Atteindre une limite ne supprime aucune donnée.</p></div></section>

<section class="marketing-section marketing-testimonial-section"><div class="marketing-container placeholder-panel"><span class="marketing-eyebrow">Preuves sociales à venir</span><h2>Les premiers témoignages seront publiés avec leur accord.</h2><p>Nous préférons une expérience réelle, datée et vérifiable à une citation inventée.</p></div></section>

<section class="marketing-section marketing-faq-section"><div class="marketing-container marketing-faq-grid"><div><span class="marketing-eyebrow">Questions fréquentes</span><h2>Les réponses avant de commencer.</h2><a class="marketing-text-link" href="{{ route('marketing.help') }}">Voir l’aide complète @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="marketing-faq-list">@foreach([['Puis-je essayer sans carte bancaire ?','L’essai de 14 jours est affiché comme un parcours gratuit. Les modalités définitives d’abonnement seront précisées avant activation.'],['WhatsApp fonctionne-t-il partout ?','La disponibilité dépend du pays, du canal configuré et du fournisseur. Le site ne promet pas une couverture universelle.'],['Que se passe-t-il quand un quota est atteint ?','L’envoi concerné s’arrête jusqu’à recharge ou renouvellement. Vos données et historiques ne sont pas supprimés.'],['Puis-je gérer plusieurs activités ?','Oui, le produit prévoit plusieurs entreprises dans un même compte, avec une séparation stricte des données.']] as $faq)<details class="marketing-faq-item"><summary>{{ $faq[0] }}<span>+</span></summary><p>{{ $faq[1] }}</p></details>@endforeach</div></div></section>

<section class="marketing-final-cta"><div class="marketing-container marketing-final-cta-inner"><div><span class="marketing-eyebrow">Prêt à voir plus clair ?</span><h2>Créez votre espace et testez le flux complet.</h2><p>14 jours pour découvrir la vente, le stock, la caisse et les reçus mobiles.</p></div><a class="marketing-button marketing-button-primary marketing-button-large" data-event="signup_start" href="{{ route('marketing.register') }}">Créer mon espace gratuitement @include('marketing.components.icon', ['name' => 'arrow'])</a></div></section>
@endsection
@section('structured-data')
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'SoftwareApplication', 'name' => 'Maxanou', 'applicationCategory' => 'BusinessApplication', 'operatingSystem' => 'Web, Android, iOS', 'description' => 'Point de vente Maxanou pour vendre, suivre le stock, piloter la caisse et envoyer des reçus mobiles.'], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'FAQPage', 'mainEntity' => array_map(fn ($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]], [['Puis-je essayer sans carte bancaire ?', 'L’essai de 14 jours est affiché comme un parcours gratuit. Les modalités définitives d’abonnement seront précisées avant activation.'], ['WhatsApp fonctionne-t-il partout ?', 'La disponibilité dépend du pays, du canal configuré et du fournisseur. Le site ne promet pas une couverture universelle.'], ['Que se passe-t-il quand un quota est atteint ?', 'L’envoi concerné s’arrête jusqu’à recharge ou renouvellement. Vos données et historiques ne sont pas supprimés.'], ['Puis-je gérer plusieurs activités ?', 'Oui, le produit prévoit plusieurs entreprises dans un même compte, avec une séparation stricte des données.']])], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endsection
