@extends('layouts.marketing')
@section('title', $content['title'].' — Maxanou')
@section('meta-description', $content['intro'])
@section('content')
<section class="marketing-page-hero"><div class="marketing-container"><span class="marketing-eyebrow">{{ $content['eyebrow'] }}</span><h1>{{ $content['title'] }}</h1><p class="marketing-lead">{{ $content['intro'] }}</p><div class="marketing-hero-actions"><a class="marketing-button marketing-button-primary" href="{{ route('marketing.register') }}">Essayer gratuitement @include('marketing.components.icon', ['name' => 'arrow'])</a><a class="marketing-button marketing-button-secondary" href="{{ route('marketing.login') }}">Se connecter</a></div></div></section>
<section class="marketing-section marketing-page-content"><div class="marketing-container"><div class="marketing-detail-grid">@foreach($content['sections'] as $item)<article class="marketing-detail-card"><span class="feature-card-icon">@include('marketing.components.icon', ['name' => $item['icon']])</span><h2>{{ $item['title'] }}</h2><p>{{ $item['text'] }}</p></article>@endforeach</div></div></section>
@if($page === 'factures-sms-whatsapp')<section class="marketing-section marketing-phone-callout"><div class="marketing-container marketing-phone-panel"><div><span class="marketing-eyebrow">Exemple fictif</span><h2>Un reçu qui ne reste pas dans la caisse.</h2><p>Les messages consomment un quota et dépendent du canal configuré. La démonstration n’utilise aucun numéro réel.</p></div><div class="phone-receipt-card"><span>Reçu · Boutique Démo</span><strong>Merci pour votre achat</strong><small>SMS · WhatsApp selon configuration</small><b>2 500 FCFA</b></div></div></section>@endif
@if(in_array($page, ['fonctionnalites','securite'], true))<section class="marketing-section marketing-page-band"><div class="marketing-container marketing-page-band-inner"><div><span class="marketing-eyebrow">Gardez le fil</span><h2>Un même produit, un même langage.</h2><p>Le site public et l’espace connecté partagent les mêmes fondations visuelles, sans charger les écrans métier dans la page marketing.</p></div><a class="marketing-button marketing-button-secondary" href="{{ route('marketing.pricing') }}">Voir les offres @include('marketing.components.icon', ['name' => 'arrow'])</a></div></section>@endif
@endsection
