@extends('layouts.marketing')
@section('title', $content['title'].' — Maxanou')
@section('meta-description', $content['intro'])
@section('content')
<section class="marketing-page-hero"><div class="marketing-container"><span class="marketing-eyebrow">{{ $content['eyebrow'] }}</span><h1>{{ $content['title'] }}</h1><p class="marketing-lead">{{ $content['intro'] }}</p>@if($page === 'partenaires')<div class="marketing-hero-actions"><a class="marketing-button marketing-button-primary" href="#partenaire-exemple">Découvrir le programme @include('marketing.components.icon', ['name' => 'arrow'])</a><a class="marketing-button marketing-button-secondary" href="{{ route('partner.login') }}">Accéder à l’espace partenaire</a></div><p class="marketing-login-note">Programme en ouverture progressive : les inscriptions seront activées après validation des conditions du programme.</p>@else<div class="marketing-hero-actions"><a class="marketing-button marketing-button-primary" href="{{ route('marketing.register') }}">Essayer gratuitement @include('marketing.components.icon', ['name' => 'arrow'])</a><a class="marketing-button marketing-button-secondary" href="{{ route('marketing.login') }}">Se connecter</a></div>@endif</div></section>
<section class="marketing-section marketing-page-content"><div class="marketing-container"><div class="marketing-detail-grid">@foreach($content['sections'] as $item)<article class="marketing-detail-card"><span class="feature-card-icon">@include('marketing.components.icon', ['name' => $item['icon']])</span><h2>{{ $item['title'] }}</h2><p>{{ $item['text'] }}</p></article>@endforeach</div></div></section>
@if($page === 'partenaires')<section class="marketing-section marketing-ecommerce-section" id="partenaire-exemple"><div class="marketing-container marketing-ecommerce-panel"><div><span class="marketing-eyebrow">Exemple concret · simulation</span><h2>Un conseil utile peut créer de la valeur pour chacun.</h2><p>Un commerçant choisit un abonnement Basic à 2 500 XOF par mois avec votre code. La remise de 10 % représente 250 XOF pour son premier abonnement ; la commission indicative de 10 % représente 250 XOF sur le montant catalogue brut.</p><a class="marketing-button marketing-button-secondary" href="#partenaire-comment-ca-marche">Voir comment commencer @include('marketing.components.icon', ['name' => 'arrow'])</a></div><div class="ecommerce-flow"><div><span>01</span><strong>Vous partagez</strong><small>Votre code partenaire</small></div><i>@include('marketing.components.icon', ['name' => 'arrow'])</i><div><span>02</span><strong>Le client économise</strong><small>2 250 XOF au premier paiement</small></div><i>@include('marketing.components.icon', ['name' => 'arrow'])</i><div><span>03</span><strong>Vous êtes commissionné</strong><small>250 XOF indicatifs</small></div></div></div></section><section class="marketing-section marketing-results-section" id="partenaire-comment-ca-marche"><div class="marketing-container"><div class="marketing-section-heading"><span class="marketing-eyebrow">Comment s’y prendre</span><h2>Commencez avec les commerçants que vous comprenez.</h2><p>Le meilleur partenaire n’est pas celui qui promet le plus : c’est celui qui aide le bon commerce à franchir la première étape.</p></div><div class="marketing-metric-grid"><div class="marketing-metric-card"><span class="metric-icon"><strong>01</strong></span><strong>Inscrivez-vous</strong><p>Créez votre espace partenaire lorsque les inscriptions sont ouvertes et complétez vos informations.</p></div><div class="marketing-metric-card"><span class="metric-icon metric-icon-green"><strong>02</strong></span><strong>Choisissez votre terrain</strong><p>Commencez par un secteur et une zone où vous connaissez les habitudes des commerçants.</p></div><div class="marketing-metric-card"><span class="metric-icon metric-icon-blue"><strong>03</strong></span><strong>Partagez avec contexte</strong><p>Expliquez le bénéfice concret : vente, stock, caisse, reçus SMS ou WhatsApp.</p></div><div class="marketing-metric-card"><span class="metric-icon metric-icon-purple"><strong>04</strong></span><strong>Suivez la relation</strong><p>Consultez vos clients attribués, vos commissions et les prochaines étapes depuis votre espace.</p></div></div></div></section>@endif
@if($page === 'factures-sms-whatsapp')<section class="marketing-section marketing-phone-callout"><div class="marketing-container marketing-phone-panel"><div><span class="marketing-eyebrow">Exemple fictif</span><h2>Un reçu qui ne reste pas dans la caisse.</h2><p>Les messages consomment un quota et dépendent du canal configuré. La démonstration n’utilise aucun numéro réel.</p></div><div class="phone-receipt-card"><span>Reçu · Boutique Démo</span><strong>Merci pour votre achat</strong><small>SMS · WhatsApp selon configuration</small><b>2 500 FCFA</b></div></div></section>@endif
@if(in_array($page, ['fonctionnalites','securite'], true))<section class="marketing-section marketing-page-band"><div class="marketing-container marketing-page-band-inner"><div><span class="marketing-eyebrow">Gardez le fil</span><h2>Un même produit, un même langage.</h2><p>Le site public et l’espace connecté partagent les mêmes fondations visuelles, sans charger les écrans métier dans la page marketing.</p></div><a class="marketing-button marketing-button-secondary" href="{{ route('marketing.pricing') }}">Voir les offres @include('marketing.components.icon', ['name' => 'arrow'])</a></div></section>@endif
@endsection
