@extends('layouts.saas')

@push('styles')
    <link rel="stylesheet" href="{{ asset('hub/assets/css/saas-pages.css') }}?v=20260902-16">
@endpush

@section('title', 'Paramètres de l’entreprise')

@section('content')
<div class="saas-page-heading"><div><span class="saas-eyebrow"><i class="bi bi-sliders" aria-hidden="true"></i> Paramètres de l’espace</span><h1>Paramètres de l’entreprise</h1><p>Gérez l’identité, les coordonnées et les services de la compagnie active.</p></div>@if($currentMembership?->role?->key === 'owner')<button type="button" class="saas-btn saas-btn-primary" data-bs-toggle="modal" data-bs-target="#addModal"><i class="bi bi-plus-lg" aria-hidden="true"></i> Ajouter une entreprise</button>@endif</div>

<div class="saas-settings-grid"><section class="saas-card saas-settings-overview"><div class="saas-card-head"><div><h2>Mes entreprises</h2><p class="saas-card-description">Ouvrez un espace existant ou créez une nouvelle entreprise. Le rôle affiché est propre à chaque entreprise.</p></div></div><div class="saas-company-grid">@foreach($memberships as $membership) @php $active = (int) $activeCompanyId === (int) $membership->company_id; @endphp<article class="saas-company-card {{ $active ? 'is-active' : '' }}"><div class="saas-company-card-head"><div class="saas-company-logo">@if($membership->company->logo)<img src="{{ asset($membership->company->logo) }}" alt="Logo de {{ $membership->company->name }}">@else{{ mb_strtoupper(mb_substr($membership->company->name, 0, 2)) }}@endif</div><div><h3>{{ $membership->company->name }}</h3><p>{{ $membership->company->email ?: 'E-mail non renseigné' }}</p></div></div><div class="saas-company-meta"><span class="saas-status-badge {{ $active ? 'is-active' : 'is-neutral' }}">{{ $active ? 'Active' : 'Disponible' }}</span><span class="saas-badge">{{ $membership->role->name ?? 'Sans rôle' }}</span></div>@if($active)<button type="button" class="saas-btn saas-btn-ghost w-100" disabled>Entreprise ouverte</button>@else<form method="POST" action="{{ route('companies.switch', $membership->company_id) }}"><input type="hidden" name="_token" value="{{ csrf_token() }}"><button class="saas-btn saas-btn-outline w-100" data-loading-text="Ouverture…">Ouvrir cette entreprise</button></form>@endif</article>@endforeach</div></section>
<aside class="saas-settings-quicklinks" aria-label="Domaines de configuration"><div class="saas-card"><div class="saas-card-head"><div><h2>Domaines</h2><p class="saas-card-description">Accédez directement aux réglages de votre entreprise.</p></div></div><nav class="saas-settings-links"><a href="#companyTable"><i class="bi bi-building" aria-hidden="true"></i><span><strong>Identité et coordonnées</strong><small>Informations générales de l’entreprise active</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a>@if(Route::has('notifications.index'))<a href="{{ route('notifications.index') }}"><i class="bi bi-chat-square-text" aria-hidden="true"></i><span><strong>Communications</strong><small>E-mail, SMS, WhatsApp et destinataires</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a>@endif @if(Route::has('ams.settings'))<a href="{{ route('ams.settings') }}"><i class="bi bi-wallet2" aria-hidden="true"></i><span><strong>Ventes et comptabilité</strong><small>Caisses et taux de taxe par défaut</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a>@endif @if(Route::has('ecommerce.settings'))<a href="{{ route('ecommerce.settings') }}"><i class="bi bi-shop" aria-hidden="true"></i><span><strong>Boutique E-commerce</strong><small>Adresse publique, logo et responsables</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a>@endif<a href="{{ route('profil') }}"><i class="bi bi-person" aria-hidden="true"></i><span><strong>Préférences personnelles</strong><small>Thème et couleur de votre interface</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a></nav></div></aside></div>

<section id="companyTable" class="saas-card"><div class="saas-card-head"><div><h2>Informations de la compagnie active</h2><p class="saas-card-description">Les actions de consultation et de modification restent limitées à la compagnie active.</p></div></div><div class="saas-table-shell"><table id="datatable" class="saas-data-table w-100"><thead><tr><th>#</th><th>Nom</th><th>E-mail</th><th>Adresse</th><th>Téléphone 1</th><th>Téléphone 2</th><th>Créée le</th><th>Actions</th></tr></thead><tbody></tbody></table></div></section>

<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalTitle" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content saas-modal-content"><div class="modal-header"><div><span class="saas-modal-eyebrow">Nouvel espace</span><h2 class="modal-title" id="addModalTitle">Ajouter une entreprise</h2></div><button type="button" class="saas-modal-close" data-bs-dismiss="modal" aria-label="Fermer"><i class="bi bi-x-lg" aria-hidden="true"></i></button></div><div class="modal-body"><form id="add" enctype="multipart/form-data"><input type="hidden" name="_token" value="{{ csrf_token() }}"><div class="saas-form-grid"><div class="saas-form-group"><label for="exampleInputText0">Nom de l’entreprise</label><input id="exampleInputText0" name="name" required></div><div class="saas-form-group"><label for="exampleInputText1">E-mail</label><input id="exampleInputText1" name="email" type="email" required></div><div class="saas-form-group"><label for="exampleInputText2">Téléphone principal</label><input id="exampleInputText2" name="number1" required></div><div class="saas-form-group"><label for="exampleInputText3">Téléphone secondaire</label><input id="exampleInputText3" name="number2"></div><div class="saas-form-group"><label for="exampleInputText4">Adresse</label><input id="exampleInputText4" name="adress"></div><div class="saas-form-group"><label for="exampleInputText5">Message d’accueil</label><input id="exampleInputText5" name="message"></div><div class="saas-form-group"><label for="add_logo">Logo <span class="saas-help">Aucun fichier n’est requis</span></label><input id="add_logo" name="logo" type="file" accept="image/*"></div><div class="saas-form-group"><label for="add_default_tax">Taxe par défaut (%)</label><input id="add_default_tax" name="default_tax" type="number" min="0" max="100" step="0.01"><small>Vous pourrez la modifier dans Comptabilité.</small></div><div class="saas-form-group saas-form-group-wide"><label for="add_description">Description E-commerce</label><textarea id="add_description" name="description" rows="3"></textarea></div></div><div class="saas-modal-actions"><button type="button" class="saas-btn saas-btn-ghost" data-bs-dismiss="modal">Annuler</button><button type="submit" class="saas-btn saas-btn-primary" data-loading-text="Création…"><i class="bi bi-check-lg" aria-hidden="true"></i> Créer l’entreprise</button></div></form></div></div></div></div>
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalTitle" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content saas-modal-content"><div class="modal-header"><div><span class="saas-modal-eyebrow">Entreprise active</span><h2 class="modal-title" id="editModalTitle">Modifier l’identité</h2></div><button type="button" class="saas-modal-close" data-bs-dismiss="modal" aria-label="Fermer"><i class="bi bi-x-lg" aria-hidden="true"></i></button></div><div class="modal-body" id="edit_response"><div class="saas-empty-state is-compact">Chargement…</div></div></div></div></div>
<div class="modal fade" id="showModal" tabindex="-1" aria-labelledby="showModalTitle" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content saas-modal-content"><div class="modal-header"><div><span class="saas-modal-eyebrow">Entreprise active</span><h2 class="modal-title" id="showModalTitle">Détails</h2></div><button type="button" class="saas-modal-close" data-bs-dismiss="modal" aria-label="Fermer"><i class="bi bi-x-lg" aria-hidden="true"></i></button></div><div class="modal-body" id="show_response"><div class="saas-empty-state is-compact">Chargement…</div></div></div></div></div>
@endsection

@push('scripts')
<script src="{{ asset('hub/assets/plugins/datatables.net/js/dataTables.min.js') }}"></script><script src="{{ asset('hub/assets/plugins/datatables.net-bs5/js/dataTables.bootstrap5.min.js') }}"></script><script src="{{ asset('hub/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script><script src="{{ asset('hub/assets/plugins/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js') }}"></script>
<script>
$(function(){const table=$('#datatable').DataTable({processing:true,serverSide:true,responsive:true,ajax:"{{ route('company.index') }}",columns:[{data:'id',name:'id'},{data:'name',name:'name'},{data:'email',name:'email'},{data:'adress',name:'adress'},{data:'number1',name:'number1'},{data:'number2',name:'number2'},{data:'created_at',name:'created_at'},{data:'action',name:'action',orderable:false,searchable:false}],language:{processing:'Chargement…',lengthMenu:'Afficher _MENU_ entrées',zeroRecords:'Aucune entreprise trouvée',emptyTable:'Aucune entreprise disponible',info:'Affichage de _START_ à _END_ sur _TOTAL_ entrées',infoEmpty:'Aucune entrée',search:'Rechercher :',paginate:{first:'Premier',last:'Dernier',next:'Suivant',previous:'Précédent'}}});
$('#add').on('submit',function(e){e.preventDefault();const form=this,button=form.querySelector('[type=submit]');window.ServerButtonLoader.withLoader(button,fetch("{{ route('company.store') }}",{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}}).then(r=>r.json()).then(data=>{if(!data.status)throw new Error(data.msg||'Création impossible');bootstrap.Modal.getInstance(document.getElementById('addModal')).hide();return Swal.fire({icon:'success',title:'Entreprise créée',text:'Voulez-vous ouvrir « '+data.company_name+' » maintenant ?',showCancelButton:true,confirmButtonText:'Oui, ouvrir',cancelButtonText:'Rester ici',buttonsStyling:false,customClass:{confirmButton:'saas-btn saas-btn-primary',cancelButton:'saas-btn saas-btn-ghost'}}).then(x=>x.isConfirmed?submitCompanySwitch(data.switch_url):location.reload())})).catch(error=>{Swal.fire({icon:'error',title:'Création impossible',text:error.message})})});
function submitCompanySwitch(url){const f=document.createElement('form');f.method='POST';f.action=url;f.innerHTML='<input type="hidden" name="_token" value="{{ csrf_token() }}">';document.body.appendChild(f);f.submit()}
$('body').on('click','.editModal,.view',function(){const id=$(this).data('id'),edit=$(this).hasClass('editModal'),target=edit?'#edit_response':'#show_response',modal=bootstrap.Modal.getOrCreateInstance(document.querySelector(edit?'#editModal':'#showModal'));$(target).html('<div class="saas-empty-state is-compact">Chargement…</div>');modal.show();fetch("{{ url('setting/company') }}/"+id+(edit?'/edit':''),{headers:{Accept:'text/html'}}).then(r=>{if(!r.ok)throw new Error('Chargement impossible');return r.text()}).then(html=>$(target).html(html)).catch(e=>$(target).html('<div class="saas-alert saas-alert-danger">'+e.message+'</div>'))});window.addEventListener('datatableUpdated',()=>table.ajax.reload(null,false));});
</script>
<script>
document.getElementById('addModal')?.addEventListener('show.bs.modal', function () {
    if (window.Swal?.isVisible()) window.Swal.close();
});
</script>
@endpush
