<?php

/*
 * Longueur nationale attendue pour les numéros utilisés par les canaux SMS et
 * WhatsApp. L'indicatif ne fait jamais partie de la valeur enregistrée : le
 * prestataire reçoit déjà le pays dans un champ séparé.
 */
return [
    'DZ' => ['dial_code' => '213', 'min_length' => 9, 'max_length' => 9],
    'AO' => ['dial_code' => '244', 'min_length' => 9, 'max_length' => 9],
    'BJ' => ['dial_code' => '229', 'min_length' => 8, 'max_length' => 8],
    'BW' => ['dial_code' => '267', 'min_length' => 7, 'max_length' => 8],
    'BF' => ['dial_code' => '226', 'min_length' => 8, 'max_length' => 8],
    'BI' => ['dial_code' => '257', 'min_length' => 8, 'max_length' => 8],
    'CV' => ['dial_code' => '238', 'min_length' => 7, 'max_length' => 7],
    'CM' => ['dial_code' => '237', 'min_length' => 9, 'max_length' => 9],
    'CF' => ['dial_code' => '236', 'min_length' => 8, 'max_length' => 8],
    'TD' => ['dial_code' => '235', 'min_length' => 8, 'max_length' => 8],
    'KM' => ['dial_code' => '269', 'min_length' => 7, 'max_length' => 7],
    'CG' => ['dial_code' => '242', 'min_length' => 9, 'max_length' => 9],
    'CD' => ['dial_code' => '243', 'min_length' => 9, 'max_length' => 9],
    'CI' => ['dial_code' => '225', 'min_length' => 10, 'max_length' => 10],
    'DJ' => ['dial_code' => '253', 'min_length' => 8, 'max_length' => 8],
    'EG' => ['dial_code' => '20', 'min_length' => 10, 'max_length' => 10],
    'GQ' => ['dial_code' => '240', 'min_length' => 9, 'max_length' => 9],
    'ER' => ['dial_code' => '291', 'min_length' => 7, 'max_length' => 7],
    'SZ' => ['dial_code' => '268', 'min_length' => 8, 'max_length' => 9],
    'ET' => ['dial_code' => '251', 'min_length' => 9, 'max_length' => 9],
    'GA' => ['dial_code' => '241', 'min_length' => 7, 'max_length' => 8],
    'GM' => ['dial_code' => '220', 'min_length' => 7, 'max_length' => 7],
    'GH' => ['dial_code' => '233', 'min_length' => 9, 'max_length' => 9],
    'GN' => ['dial_code' => '224', 'min_length' => 9, 'max_length' => 9],
    'GW' => ['dial_code' => '245', 'min_length' => 7, 'max_length' => 7],
    'KE' => ['dial_code' => '254', 'min_length' => 9, 'max_length' => 9],
    'LS' => ['dial_code' => '266', 'min_length' => 8, 'max_length' => 8],
    'LR' => ['dial_code' => '231', 'min_length' => 7, 'max_length' => 9],
    'LY' => ['dial_code' => '218', 'min_length' => 9, 'max_length' => 9],
    'MG' => ['dial_code' => '261', 'min_length' => 9, 'max_length' => 9],
    'MW' => ['dial_code' => '265', 'min_length' => 9, 'max_length' => 9],
    'ML' => ['dial_code' => '223', 'min_length' => 8, 'max_length' => 8],
    'MR' => ['dial_code' => '222', 'min_length' => 8, 'max_length' => 8],
    'MU' => ['dial_code' => '230', 'min_length' => 8, 'max_length' => 8],
    'MA' => ['dial_code' => '212', 'min_length' => 9, 'max_length' => 9],
    'MZ' => ['dial_code' => '258', 'min_length' => 9, 'max_length' => 9],
    'NA' => ['dial_code' => '264', 'min_length' => 9, 'max_length' => 9],
    'NE' => ['dial_code' => '227', 'min_length' => 8, 'max_length' => 8],
    'NG' => ['dial_code' => '234', 'min_length' => 10, 'max_length' => 10],
    'RW' => ['dial_code' => '250', 'min_length' => 9, 'max_length' => 9],
    'ST' => ['dial_code' => '239', 'min_length' => 7, 'max_length' => 7],
    'SN' => ['dial_code' => '221', 'min_length' => 9, 'max_length' => 9],
    'SC' => ['dial_code' => '248', 'min_length' => 7, 'max_length' => 7],
    'SL' => ['dial_code' => '232', 'min_length' => 8, 'max_length' => 8],
    'SO' => ['dial_code' => '252', 'min_length' => 8, 'max_length' => 9],
    'ZA' => ['dial_code' => '27', 'min_length' => 9, 'max_length' => 9],
    'SS' => ['dial_code' => '211', 'min_length' => 9, 'max_length' => 9],
    'SD' => ['dial_code' => '249', 'min_length' => 9, 'max_length' => 9],
    'TZ' => ['dial_code' => '255', 'min_length' => 9, 'max_length' => 9],
    'TG' => ['dial_code' => '228', 'min_length' => 8, 'max_length' => 8],
    'TN' => ['dial_code' => '216', 'min_length' => 8, 'max_length' => 8],
    'UG' => ['dial_code' => '256', 'min_length' => 9, 'max_length' => 9],
    'ZM' => ['dial_code' => '260', 'min_length' => 9, 'max_length' => 9],
    'ZW' => ['dial_code' => '263', 'min_length' => 9, 'max_length' => 9],
];
