@extends('layouts.platform')
@section('title','Alertes opérationnelles')
@section('page-title','Alertes opérationnelles')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><p class="text-secondary mb-0">Surveillance des queues, paiements et communications.</p><form method="POST" action="{{ route('platform.alerts.check') }}">@csrf<button class="btn btn-outline-warning" data-loading-text="Vérification…"><i class="bi bi-arrow-repeat me-1"></i>Vérifier maintenant</button></form></div>
@if(auth('platform')->user()->hasPlatformPermission('platform.admins.manage'))
<div class="platform-card p-4 mb-4"><h2 class="h5">Configuration</h2><form method="POST" action="{{ route('platform.alerts.settings') }}">@csrf @method('PUT')
<div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" id="enabled" name="enabled" value="1" @checked($settings->enabled)><label class="form-check-label" for="enabled">Activer la surveillance et les e-mails d’alerte</label></div>
<div class="row g-3">
<div class="col-md-4"><label class="form-label">Jobs échoués</label><input class="form-control" type="number" name="failed_jobs_threshold" min="1" value="{{ $settings->failed_jobs_threshold }}" required></div>
<div class="col-md-4"><label class="form-label">Ancienneté queue (minutes)</label><input class="form-control" type="number" name="queue_age_minutes" min="1" value="{{ $settings->queue_age_minutes }}" required></div>
<div class="col-md-4"><label class="form-label">Paiement bloqué (minutes)</label><input class="form-control" type="number" name="blocked_payment_minutes" min="10" value="{{ $settings->blocked_payment_minutes }}" required></div>
<div class="col-md-4"><label class="form-label">Échecs communications (%)</label><input class="form-control" type="number" name="delivery_failure_percent" min="1" max="100" value="{{ $settings->delivery_failure_percent }}" required></div>
<div class="col-md-4"><label class="form-label">Volume minimum</label><input class="form-control" type="number" name="delivery_minimum_volume" min="1" value="{{ $settings->delivery_minimum_volume }}" required></div>
<div class="col-md-4"><label class="form-label">Anti-spam (minutes)</label><input class="form-control" type="number" name="cooldown_minutes" min="5" value="{{ $settings->cooldown_minutes }}" required></div></div>
<div class="mt-3"><label class="form-label">Destinataires e-mail</label><div class="row">@foreach($admins as $admin)<div class="col-md-6"><label class="form-check"><input class="form-check-input" type="checkbox" name="recipient_admin_ids[]" value="{{ $admin->id }}" @checked(in_array($admin->id,$settings->recipient_admin_ids ?? []))><span class="form-check-label">{{ $admin->name }} — {{ $admin->roleLabel() }}</span></label></div>@endforeach</div><div class="form-text">Sans sélection, tous les super-administrateurs et techniciens actifs seront alertés.</div></div>
<div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label">Motif</label><input class="form-control" name="reason" minlength="5" required></div><div class="col-md-6"><label class="form-label">Votre mot de passe</label><input class="form-control" type="password" name="current_password" required></div></div><button class="btn btn-warning mt-3" data-loading-text="Enregistrement…">Enregistrer la surveillance</button></form></div>
@endif
<div class="platform-card p-3"><h2 class="h5 mb-3">Historique</h2><div class="table-responsive"><table class="table table-dark align-middle"><thead><tr><th>Incident</th><th>État</th><th>Détection</th><th>Notification</th><th>Actions</th></tr></thead><tbody>
@forelse($alerts as $alert)<tr><td><strong>{{ $alert->title }}</strong><br><small class="text-secondary">{{ $alert->message }}</small></td><td><span class="badge {{ $alert->status==='resolved'?'bg-success':($alert->status==='acknowledged'?'bg-info text-dark':'bg-danger') }}">{{ ['open'=>'Ouverte','acknowledged'=>'Prise en charge','resolved'=>'Résolue'][$alert->status] ?? $alert->status }}</span></td><td>{{ $alert->last_detected_at->format('d/m/Y H:i') }}</td><td>{{ $alert->last_notified_at?->format('d/m/Y H:i') ?? 'Non envoyée' }}</td><td><div class="d-flex gap-2">@if($alert->status==='open')<form method="POST" action="{{ route('platform.alerts.acknowledge',$alert) }}">@csrf<button class="btn btn-sm btn-outline-info" data-loading-text="…">Prendre en charge</button></form>@endif @if($alert->status!=='resolved')<button class="btn btn-sm btn-outline-success resolve-alert" data-url="{{ route('platform.alerts.resolve',$alert) }}">Résoudre</button>@endif</div></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Aucune alerte enregistrée.</td></tr>@endforelse
</tbody></table></div>{{ $alerts->links() }}</div>
@endsection
@push('scripts')<script>document.querySelectorAll('.resolve-alert').forEach(b=>b.addEventListener('click',()=>Swal.fire({title:'Marquer cette alerte comme résolue ?',input:'text',inputPlaceholder:'Décrivez la résolution',showCancelButton:true,confirmButtonText:'Résoudre',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),inputValidator:v=>!v||v.trim().length<5?'Motif de 5 caractères minimum.':null,preConfirm:async reason=>{const r=await fetch(b.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({reason})});const d=await r.json().catch(()=>({}));if(!r.ok)return Swal.showValidationMessage(d.message||'Opération impossible.');return d}}).then(r=>{if(r.isConfirmed)location.reload()})));</script>@endpush
