@extends('layouts.platform')
@section('title', 'Paiement '.$payment->transaction_id)
@section('page-title', 'Détail du paiement')
@section('content')
<div class="d-flex justify-content-between gap-2 mb-4"><a href="{{ route('platform.payments.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Paiements</a>@if($payment->status !== 'paid')<button class="btn btn-outline-warning" id="reconcilePayment" data-url="{{ route('platform.payments.reconcile',$payment) }}"><i class="bi bi-arrow-repeat me-1"></i>Vérifier chez KPrimePay</button>@endif</div>
<div class="row g-4"><div class="col-xl-7"><div class="platform-card p-4"><h2 class="h5 mb-3">Transaction</h2><dl class="row mb-0"><dt class="col-5">Référence interne</dt><dd class="col-7 text-break">{{ $payment->transaction_id }}</dd><dt class="col-5">Référence KPrimePay</dt><dd class="col-7 text-break">{{ $payment->kpp_reference ?: 'Non reçue' }}</dd><dt class="col-5">Statut</dt><dd class="col-7"><span class="badge {{ $payment->status==='paid'?'bg-success':(in_array($payment->status,['failed','expired'])?'bg-danger':'bg-warning text-dark') }}">{{ $payment->status }}</span></dd><dt class="col-5">Montant</dt><dd class="col-7">{{ number_format($payment->amount,0,',',' ') }} {{ $payment->currency }}</dd><dt class="col-5">Création</dt><dd class="col-7">{{ $payment->created_at?->format('d/m/Y H:i:s') }}</dd><dt class="col-5">Confirmation</dt><dd class="col-7">{{ $payment->paid_at?->format('d/m/Y H:i:s') ?? 'Non confirmée' }}</dd><dt class="col-5">Erreur</dt><dd class="col-7">{{ $payment->failure_reason ?: 'Aucune' }}</dd></dl></div></div><div class="col-xl-5"><div class="platform-card p-4"><h2 class="h5 mb-3">Entreprise et quotas</h2><p><a href="{{ $payment->company ? route('platform.companies.show',$payment->company) : '#' }}" class="fw-semibold text-decoration-none">{{ $payment->company?->name ?? 'Entreprise supprimée' }}</a></p><div class="row g-3"><div class="col-6"><div class="border rounded p-3"><div class="metric-value">{{ $payment->sms_quantity }}</div><small>SMS à créditer</small><br><small class="text-secondary">{{ $payment->sms_unit_price !== null ? $payment->sms_unit_price.' XOF/unité' : 'Ancien tarif' }}</small></div></div><div class="col-6"><div class="border rounded p-3"><div class="metric-value">{{ $payment->whatsapp_quantity }}</div><small>WhatsApp à créditer</small><br><small class="text-secondary">{{ $payment->whatsapp_unit_price !== null ? $payment->whatsapp_unit_price.' XOF/unité' : 'Ancien tarif' }}</small></div></div></div><p class="text-secondary small mt-3 mb-0">Demande initiée par {{ $payment->user?->name ?? 'Utilisateur supprimé' }} ({{ $payment->user?->email }}).</p></div></div></div>
@endsection
@push('scripts')
@if($payment->status !== 'paid')<script>document.getElementById('reconcilePayment')?.addEventListener('click',function(){const button=this;Swal.fire({title:'Vérifier ce paiement ?',text:'Le statut sera demandé directement à KPrimePay. Aucun crédit manuel ne sera effectué.',icon:'question',input:'textarea',inputLabel:'Motif obligatoire',inputPlaceholder:'Ex. : paiement signalé par le client…',showCancelButton:true,confirmButtonText:'Oui, vérifier',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),allowEscapeKey:()=>!Swal.isLoading(),preConfirm:async(reason)=>{if(!reason||reason.trim().length<5)return Swal.showValidationMessage('Indiquez un motif d’au moins 5 caractères.');const response=await fetch(button.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({reason:reason.trim()})});const data=await response.json().catch(()=>({}));if(!response.ok)return Swal.showValidationMessage(data.message||'Vérification impossible.');return data;}}).then(result=>{if(result.isConfirmed)Swal.fire({icon:'success',title:'Vérification terminée',text:result.value.message}).then(()=>location.reload());});});</script>@endif
@endpush
