@extends('layouts.platform')
@section('title', 'Utilisateurs')
@section('page-title', 'Utilisateurs de la plateforme')
@section('content')
<div class="platform-card p-3 mb-4"><form method="GET" class="row g-3 align-items-end"><div class="col-lg-7"><label class="form-label" for="q">Recherche</label><input id="q" name="q" class="form-control" value="{{ request('q') }}" placeholder="Nom, e-mail ou téléphone"></div><div class="col-lg-3"><label class="form-label" for="status">Statut</label><select id="status" name="status" class="form-select"><option value="">Tous</option><option value="active" @selected(request('status') === 'active')>Actifs</option><option value="inactive" @selected(request('status') === 'inactive')>Désactivés</option></select></div><div class="col-lg-2 d-grid"><button class="btn btn-warning" data-loading-text="Recherche…"><i class="bi bi-search me-1"></i> Rechercher</button></div></form></div>
<div class="platform-card p-3"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">{{ number_format($users->total(), 0, ',', ' ') }} utilisateur(s)</h2>@if(request()->hasAny(['q','status']))<a href="{{ route('platform.users.index') }}" class="btn btn-sm btn-outline-secondary">Réinitialiser</a>@endif</div><div class="table-responsive"><table class="table table-dark table-hover align-middle"><thead><tr><th>Utilisateur</th><th>Téléphone</th><th>Statut</th><th>Entreprises</th><th>État des adhésions</th><th>Dernier accès</th><th>Inscription</th><th></th></tr></thead><tbody>
@forelse($users as $user)@php($inactiveMemberships = max(0, $user->memberships_count - $user->active_memberships_count))<tr><td><div class="fw-semibold">{{ $user->name }}</div><small class="text-secondary">{{ $user->email }}</small></td><td>{{ $user->phone ?: 'Non renseigné' }}</td><td><span class="badge {{ (int)$user->status === 1 ? 'bg-success' : 'bg-danger' }}">{{ (int)$user->status === 1 ? 'Actif' : 'Désactivé' }}</span></td><td><div class="d-flex flex-wrap gap-1" style="min-width:170px">@forelse($user->memberships as $membership)@if($membership->company)<a href="{{ route('platform.companies.show', $membership->company) }}" class="badge text-decoration-none {{ $membership->status === 'active' ? 'bg-info text-dark' : 'bg-secondary' }}" title="Adhésion {{ $membership->status }}">{{ $membership->company->name }}</a>@endif @empty<span class="text-secondary">Aucune entreprise</span>@endforelse</div></td><td><div class="d-flex flex-column gap-1 align-items-start">@if($user->memberships_count === 0)<span class="badge bg-secondary">Aucune adhésion</span>@else<span class="badge bg-success">{{ $user->active_memberships_count }} active(s) sur {{ $user->memberships_count }}</span>@if($inactiveMemberships > 0)<span class="badge bg-danger">{{ $inactiveMemberships }} inactive(s)</span>@endif @endif</div></td><td>{{ $user->memberships_max_last_accessed_at ? \Carbon\Carbon::parse($user->memberships_max_last_accessed_at)->format('d/m/Y H:i') : 'Jamais' }}</td><td>{{ $user->created_at?->format('d/m/Y') }}</td><td><a href="{{ route('platform.users.show', $user) }}" class="btn btn-sm btn-outline-info"><i class="bi bi-eye me-1"></i>Consulter</a></td></tr>
@empty<tr><td colspan="8" class="text-center text-secondary py-5">Aucun utilisateur ne correspond aux critères.</td></tr>@endforelse
</tbody></table></div><div class="mt-3">{{ $users->links() }}</div></div>
@endsection
