@extends('layouts.platform')
@section('title', 'Santé du système')
@section('page-title', 'Santé du système')
@section('content')
@php($schedulerLabels=['healthy'=>['Opérationnel','success'],'warning'=>['En retard','warning'],'critical'=>['Critique','danger'],'unknown'=>['Non observé','secondary']])
<div class="row g-3 mb-4"><div class="col-md-6 col-xl-3"><div class="platform-card p-3 h-100"><span class="badge bg-{{ $schedulerLabels[$schedulerStatus][1] }}">{{ $schedulerLabels[$schedulerStatus][0] }}</span><div class="metric-value mt-2">Cron Laravel</div><div class="metric-label">{{ $heartbeat ? 'Dernier passage il y a '.$heartbeatAge.' min' : 'Lancez platform:heartbeat ou schedule:run' }}</div></div></div><div class="col-md-6 col-xl-3"><div class="platform-card p-3 h-100"><span class="badge {{ $queue['pending']>100?'bg-warning text-dark':'bg-info text-dark' }}">File</span><div class="metric-value mt-2">{{ $queue['pending'] }}</div><div class="metric-label">Jobs en attente @if($queue['oldest_minutes']!==null)· plus ancien {{ $queue['oldest_minutes'] }} min @endif</div></div></div><div class="col-md-6 col-xl-3"><div class="platform-card p-3 h-100"><span class="badge {{ $queue['failed']>0?'bg-danger':'bg-success' }}">Échecs</span><div class="metric-value mt-2">{{ $queue['failed'] }}</div><div class="metric-label">Jobs échoués</div></div></div><div class="col-md-6 col-xl-3"><div class="platform-card p-3 h-100"><span class="badge {{ $blockedPayments>0?'bg-warning text-dark':'bg-success' }}">KPrimePay</span><div class="metric-value mt-2">{{ $blockedPayments }}</div><div class="metric-label">Paiements en attente depuis plus de 2 h · {{ $webhookPayments }} avec webhook sur 7 jours</div></div></div></div>

<div class="platform-card p-3 mb-4"><h2 class="h5 mb-1">Délivrabilité sur les 7 derniers jours</h2><p class="text-secondary small">Suivi des destinataires configurés pour les ventes et inventaires.</p><div class="table-responsive"><table class="table table-dark align-middle mb-0"><thead><tr><th>Canal</th><th>En attente</th><th>En traitement</th><th>Envoyés</th><th>Échoués</th><th>Total</th></tr></thead><tbody>@forelse($deliveryStats->groupBy('channel') as $channel=>$rows)@php($counts=$rows->pluck('total','status'))<tr><td class="text-uppercase fw-semibold">{{ strtoupper($channel) }}</td><td>{{ $counts['pending']??0 }}</td><td>{{ $counts['processing']??0 }}</td><td class="text-success">{{ $counts['sent']??0 }}</td><td class="text-danger">{{ $counts['failed']??0 }}</td><td>{{ $rows->sum('total') }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">Aucune livraison enregistrée sur cette période.</td></tr>@endforelse</tbody></table></div></div>

<div class="platform-card p-3"><div class="d-flex justify-content-between"><div><h2 class="h5 mb-1">Jobs échoués récents</h2><p class="small text-secondary">La relance remet le job dans la file ; elle ne garantit pas sa réussite.</p></div></div><div class="table-responsive"><table class="table table-dark table-hover align-middle"><thead><tr><th>Date</th><th>File</th><th>Connexion</th><th>Identifiant</th><th></th></tr></thead><tbody>@forelse($failedJobs as $job)<tr><td>{{ \Carbon\Carbon::parse($job->failed_at)->format('d/m/Y H:i:s') }}</td><td>{{ $job->queue }}</td><td>{{ $job->connection }}</td><td><small>{{ $job->uuid }}</small></td><td><button class="btn btn-sm btn-outline-warning retry-job" data-url="{{ route('platform.health.jobs.retry',$job->uuid) }}"><i class="bi bi-arrow-repeat me-1"></i>Relancer</button></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Aucun job échoué.</td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('.retry-job').forEach(button=>button.addEventListener('click',()=>Swal.fire({title:'Relancer ce job ?',text:'Vérifiez d’abord que la cause de l’échec est corrigée.',icon:'warning',input:'textarea',inputLabel:'Motif obligatoire',showCancelButton:true,confirmButtonText:'Oui, relancer',cancelButtonText:'Annuler',showLoaderOnConfirm:true,allowOutsideClick:()=>!Swal.isLoading(),preConfirm:async reason=>{if(!reason||reason.trim().length<5)return Swal.showValidationMessage('Indiquez un motif d’au moins 5 caractères.');const r=await fetch(button.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({reason:reason.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok)return Swal.showValidationMessage(d.message||'Relance impossible.');return d}}).then(result=>{if(result.isConfirmed)Swal.fire({icon:'success',title:'Job relancé',text:result.value.message}).then(()=>location.reload())})));</script>@endpush
